=== CR9C/JavaSE/base/src/io/github/cr9c/day02/xml/contact.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--新建一个后缀叫dtd的xml文件,写入一下内容-->
<!-- 标签名称 (规范) -->
<!ELEMENT contacts (linkman*)>
<!-- 有序标签 -->
<!ELEMENT linkman (name,email,address,group)>
<!-- 标签名称(需要解析的字符数据) -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!-- 标签名 属性名称 属性类型 默认值  -->
<!--
    ID  表示唯一
    #REQUIRED 表示必填
-->
<!ATTLIST linkman id ID #REQUIRED>

=== CR9C/JavaSE/base/src/io/github/cr9c/day02/xml/contact.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- <!DOCTYPE contacts 
	SYSTEM "contact.dtd"> --><!-- xmlns="www.520it.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="www.520it.com 
	contact.xsd"> --><contacts>
	<linkman id="a1">
		<name>西门官人</name>
		<email>xy@163.com</email>
		<address>大西门</address>
		<group>水浒</group>
	</linkman>
	<linkman id="a2">
		<name>东方姑娘</name>
		<email>dongfang@163.com</email>
		<address>黑木崖</address>
		<group>笑傲江湖</group>
	</linkman>
	<linkman id="8527">
		<name>宝宝</name>
		<email>bb@126.com</email>
		<address>帝都</address>
		<group>演员</group>
	</linkman>
	<linkman>
		<name>宝宝</name>
		<email>bb@126.com</email>
		<address>帝都</address>
		<group>演员</group>
	</linkman>
<linkman><name>宝宝</name><email>bb@126.com</email><address>帝都</address><group>演员</group></linkman></contacts>

=== CR9C/JavaSE/base/src/io/github/cr9c/day02/xml/contact11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts SYSTEM "contact.dtd">
<contacts>
	<linkman id="a1">
		<name>西门官人</name>
		<email>ximen@163.com</email>
		<address>大西门</address>
		<group>水浒</group>
	</linkman>
	<linkman id="a2">
		<name>东方姑娘</name>
		<email>dongfang@163.com</email>
		<address>黑木崖</address>
		<group>笑傲江湖</group>
	</linkman>
</contacts>
